//! Scannerless SQL grammar and its borrowed, named parse tree.
//!
//! [`parse`] consumes the whole input. Nodes retain matched input slices and
//! UTF-8 byte spans; silent rules omit punctuation, trivia, and most keywords
//! from the tree. Use [`crate::parse_sql`] for an AST instead of a parse tree.
peg::grammar!(
    r#"
Root <- _ws (Statement (_semi Statement)* _semi?)?;
Statement <- Select / CreateTable / Insert / Update / Delete / Begin / Commit / Rollback;
Select <- _select Projection From? Where?;
Projection <- Star / Expr (_comma Expr)*;
Star <- '*' _ws;
From <- _from Identifier _ws;
Where <- _where Expr;
CreateTable <- _create _table Identifier _ws _lp ColumnDef (_comma ColumnDef)* _rp;
ColumnDef <- Identifier _ws DataType Constraint*;
DataType <- IntegerType / BigIntType / TextType / BooleanType / RealType / DoubleType / VarcharType;
IntegerType <- ('INTEGER'i / 'INT'i) !_ident_rest _ws;
BigIntType <- 'BIGINT'i !_ident_rest _ws;
TextType <- 'TEXT'i !_ident_rest _ws;
BooleanType <- ('BOOLEAN'i / 'BOOL'i) !_ident_rest _ws;
RealType <- 'REAL'i !_ident_rest _ws;
DoubleType <- 'DOUBLE'i !_ident_rest _ws;
VarcharType <- 'VARCHAR'i !_ident_rest _ws (_lp Length _ws _rp)?;
Length <- [0-9]+;
Constraint <- NotNull / PrimaryKey / Unique;
NotNull <- _not _null;
PrimaryKey <- _primary _key;
Unique <- _unique;
Insert <- _insert _into Identifier _ws Columns? _values Row (_comma Row)*;
Columns <- _lp Identifier _ws (_comma Identifier _ws)* _rp;
Row <- _lp Expr (_comma Expr)* _rp;
Update <- _update Identifier _ws _set Assignment (_comma Assignment)* Where?;
Assignment <- Identifier _ws '=' _ws Expr;
Delete <- _delete _from Identifier _ws Where?;
Begin <- _begin;
Commit <- _commit;
Rollback <- _rollback;
Expr <- Or;
Or <- And (OrOp And)*;
OrOp <- _or;
And <- Not (AndOp Not)*;
AndOp <- _and;
Not <- (NotOp Not) / Comparison;
NotOp <- _not;
Comparison <- Additive (CompareOp Additive / IsNull)?;
CompareOp <- ('<=' / '>=' / '<>' / '!=' / '=' / '<' / '>') _ws;
IsNull <- _is IsNot? _null;
IsNot <- _not;
Additive <- Multiplicative (AddOp Multiplicative)*;
AddOp <- ('+' / '-') _ws;
Multiplicative <- Unary (MulOp Unary)*;
MulOp <- ('*' / '/' / '%') _ws;
Unary <- (UnaryOp Unary) / Primary;
UnaryOp <- ('+' / '-') _ws;
Primary <- Number _ws / String _ws / Null / True / False / Name / (_lp Expr _rp);
Name <- Identifier _ws ('.' _ws Identifier _ws)?;
Number <- ([0-9]+ ('.' [0-9]+)? / '.' [0-9]+) ([eE] [+-]? [0-9]+)? !_ident_rest;
String <- "'" ("''" / (!"'" .))* "'";
Null <- _null;
True <- _true;
False <- _false;
Identifier <- QuotedIdentifier / BareIdentifier;
QuotedIdentifier <- '"' ('""' / (!'"' .))+ '"';
BareIdentifier <- !_reserved [a-zA-Z_] _ident_rest*;
_ident_rest <- [a-zA-Z_0-9];
_reserved <- ('SELECT'i / 'FROM'i / 'WHERE'i / 'CREATE'i / 'TABLE'i / 'INSERT'i / 'INTO'i / 'VALUES'i / 'UPDATE'i / 'SET'i / 'DELETE'i / 'BEGIN'i / 'COMMIT'i / 'ROLLBACK'i / 'OR'i / 'AND'i / 'NOT'i / 'IS'i / 'NULL'i / 'TRUE'i / 'FALSE'i / 'PRIMARY'i / 'KEY'i / 'UNIQUE'i / 'ORDER'i / 'BY'i / 'LIMIT'i / 'JOIN'i / 'AS'i / 'GROUP'i / 'HAVING'i / 'UNION'i / 'DISTINCT'i) !_ident_rest;
_select <- 'SELECT'i !_ident_rest _ws;
_from <- 'FROM'i !_ident_rest _ws;
_where <- 'WHERE'i !_ident_rest _ws;
_create <- 'CREATE'i !_ident_rest _ws;
_table <- 'TABLE'i !_ident_rest _ws;
_insert <- 'INSERT'i !_ident_rest _ws;
_into <- 'INTO'i !_ident_rest _ws;
_values <- 'VALUES'i !_ident_rest _ws;
_update <- 'UPDATE'i !_ident_rest _ws;
_set <- 'SET'i !_ident_rest _ws;
_delete <- 'DELETE'i !_ident_rest _ws;
_begin <- 'BEGIN'i !_ident_rest _ws;
_commit <- 'COMMIT'i !_ident_rest _ws;
_rollback <- 'ROLLBACK'i !_ident_rest _ws;
_or <- 'OR'i !_ident_rest _ws;
_and <- 'AND'i !_ident_rest _ws;
_not <- 'NOT'i !_ident_rest _ws;
_is <- 'IS'i !_ident_rest _ws;
_null <- 'NULL'i !_ident_rest _ws;
_true <- 'TRUE'i !_ident_rest _ws;
_false <- 'FALSE'i !_ident_rest _ws;
_primary <- 'PRIMARY'i !_ident_rest _ws;
_key <- 'KEY'i !_ident_rest _ws;
_unique <- 'UNIQUE'i !_ident_rest _ws;
_lp <- '(' _ws;
_rp <- ')' _ws;
_comma <- ',' _ws;
_semi <- ';' _ws;
_ws <- ([ \t\r\n] / _line_comment / _block_comment)*;
_line_comment <- '--' (!'\n' .)* ('\n' / !.);
_block_comment <- '/*' (!'*/' .)* '*/';
"#
);
